version: "3"
services:
  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    network_mode: "host"
    restart: always
    volumes:
      - ./etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock