version: "3"
services:
  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    restart: always
    volumes:
      - ./etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080

  monitor:
    image: google/cadvisor
    container_name: monitor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:monitor.localhost"

networks:
  default:
    external: 
      name: 'traefik'